name: ipl_poll
description: IPL Poll App - Predict matches and win coins.
publish_to: 'none'
version: 1.0.5+5

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # HTTP client
  dio: ^5.4.0

  # State management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.4

  # Secure token storage
  flutter_secure_storage: ^9.0.0

  # Navigation
  go_router: ^13.2.0

  # Firebase
  firebase_core: ^3.8.1
  firebase_messaging: ^15.2.1
  firebase_remote_config: ^5.2.1
  flutter_local_notifications: ^18.0.1

  # UI helpers
  intl: ^0.19.0
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.8
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
